### PR TITLE
Search Sub Dirs for including classes

### PR DESCRIPTION
**Pull request by B0zy**

### CODE REVIEW

**Comment by bleonheart** [comment]
Give me an example of how this would applied, please?

**Comment by B0zy** [comment]
Allows you to just categorize Class files inside the classes folder under other folders. Say if you have 30 classes at a point it becomes cancer to keep track of what is part of what etc.

**Comment by bleonheart** [comment]
Give me an proper execution of that, I am a bit confused on how that'd work

**Comment by B0zy** [comment]
Assume this  is your class folder structure 
```
📦classes
 ┣ 📂coolguys
 ┃ ┣ 📜class
 ┃ ┣ 📜class1
 ┃ ┣ 📜class2
 ┃ ┣ 📜class3
 ┃ ┗ 📜class55
 ┣ 📜class15315
 ┗ 📜class2345
 ```
 and lets assume theres like 5x the amount of files in there, it would just automatically look for sub folders in the classes folder that have class files inside of em. I don't really know how to explain it more proper

**Comment by bleonheart** [comment]
I'd approve this, my own condition is that you:

- This should only be applied if the folder is called subclasses

- Do the same for subfactions

**Comment by B0zy** [comment]
👍 I'll work on the quickly

**Pull request closed without merging**
