### PR TITLE
Add config Options for disabling lua_run on maps

### PR DESCRIPTION
**Pull request by B0zy**

### CODE REVIEW

**Comment by bleonheart** [comment]
Where documentation? smh

**Review by bleonheart — CHANGES_REQUESTED** [review]
Add the documentation for that

**Comment by B0zy** [comment]
Will do

**Comment by bleonheart** [comment]
You are missing a not [here](https://github.com/LiliaFramework/Lilia/pull/51/files#diff-d9d05049dcbdfebfc51a1123fc9c3e0c63b1c51d6ae2c5ce896730af873552f1R54)

**Pull request merged**
