### PR TITLE
fix broken ent iteration

### PR DESCRIPTION
**Pull request by sn-0w**
there seems to be some messed up code ^^

### CODE REVIEW

**Comment by sn-0w** [comment]
And some more uses of ent.Iterator() and player.Iterator() . The function does not return a list of entities but a Iterator for iteration over the entities so its not possible to do #player.Iterator() to get the playercount!!!

**Comment by B0zy** [comment]
God bless snow I'm not longer needed to ginny pig fix it

**Comment by sn-0w** [comment]
F*CK I COMMITED MY .gitignore AGAIN....................

**Comment by bleonheart** [comment]
> there seems to be some messed up code ^^

Yeah, I was trying to understand when and not when to use Iterator, as it seems to be way more perfomance effective, I'll merge in a few, just tidying up some parts

**Comment by bleonheart** [comment]
Can you please resolve the conflicts before I merge

**Pull request closed without merging**
